targets:
  $default:
    builders:
      drift_dev:
        options:
          sqlite:
            version: "3.38"
            modules:
              - fts5
      json_serializable:
        options:
          field_rename: snake
