/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#6750A4',
        'primary-light': '#958DA5',
        'primary-dark': '#4F378B',
        secondary: '#625B71',
        'secondary-light': '#958DA5',
        tertiary: '#7D5260',
        'tertiary-light': '#B58392',
        'on-primary': '#FFFFFF',
        'on-secondary': '#FFFFFF',
        'on-tertiary': '#FFFFFF',
        'on-surface': '#1C1B1F',
        'on-surface-variant': '#49454F',
        'on-error': '#FFFFFF',
        'error': '#B3261E',
        'error-container': '#F9DEDC',
        'success': '#2E7D32',
        'warning': '#ED6C02',
        'surface-base': '#FFFBFE',
        'surface-container': '#F3EDF7',
        'surface-container-high': '#E8DEF8',
        'surface-container-highest': '#E6E0E9',
        'surface-container-low': '#F7F2FA',
        'surface-container-lowest': '#FEF7FF',
        'primary-container': '#EADDFF',
        'secondary-container': '#E8DEF8',
        'tertiary-container': '#FFD8E4',
        'on-primary-container': '#21005D',
        'on-secondary-container': '#1D192B',
        'on-tertiary-container': '#31111D',
        'outline': '#CAC4D0',
        'outline-variant': '#E7E0EC',
        'background': '#FFFBFE',
        'text-primary': '#1C1B1F',
        'text-secondary': '#49454F',
        'text-disabled': '#9E9E9E',
      },
      borderRadius: {
        'none': '0',
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
        '2xl': '28px',
        '3xl': '32px',
        'full': '9999px',
      },
      boxShadow: {
        'elevation-1': '0 1px 3px 1px rgba(0,0,0,0.15), 0 1px 2px 0 rgba(0,0,0,0.3)',
        'elevation-2': '0 2px 6px 2px rgba(0,0,0,0.15), 0 1px 2px 0 rgba(0,0,0,0.3)',
        'elevation-3': '0 4px 8px 3px rgba(0,0,0,0.15), 0 1px 3px 0 rgba(0,0,0,0.3)',
        'elevation-4': '0 6px 10px 4px rgba(0,0,0,0.15), 0 2px 3px 0 rgba(0,0,0,0.3)',
        'elevation-5': '0 8px 12px 6px rgba(0,0,0,0.15), 0 4px 4px 0 rgba(0,0,0,0.3)',
        'button': '0 1px 2px 0 rgba(0,0,0,0.3)',
        'button-hover': '0 2px 3px 1px rgba(0,0,0,0.3)',
      },
      fontFamily: {
        sans: ['Google Sans', 'Roboto', 'Inter', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        'slide-up': 'slideUp 0.6s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}