ALTER TABLE proposals ADD COLUMN IF NOT EXISTS budget_estimated DECIMAL(12,2);
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS budget_actual DECIMAL(12,2);
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS budget_currency VARCHAR(3) DEFAULT 'USD';
